  
package:
  name: hiawatha-webserver
  version: 11.1
  description: "hiawatha"
  target-architecture:
    - all
environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - http://dl-cdn.alpinelinux.org/alpine/v3.8/main
      - http://dl-cdn.alpinelinux.org/alpine/v3.8/community
    packages:
      - alpine-baselayout-data
      - busybox
      - musl-dev 
      - gcc 
      - cmake 
      - make 
      - libtool 
      - libc6-compat 
      - pcre-dev  
      - wget
      - tar
      - cmake 
      - make 
      - musl-dev 
      - libxml2-dev 
      - libxslt-dev 
      - util-linux 
      - php7-json 
      - php7-fpm

  accounts:
    groups:
      - groupname: nginx
        gid: 10000
    users:
      - username: nginx
        uid: 10000

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.com/hsleisink/hiawatha.git
      branch: master
  - uses: cmake/configure
  - uses: cmake/build
  - uses: cmake/install
  - uses: strip    
  - name: Create directory    
    run: |
       cd hiawatha
       mkdir -p build && cd build
       cmake ..
       make install/strip 
   